### ISSUE TITLE
Use factory States

### ISSUE THREAD

**Issue by AlanHolmes** [lukeraymonddowning/poser#1]
I like that this is using Laravel Factories under the hood, which leads me onto this request:

Having support for using the Factory States.

I have used the states heavily, so to be able to continue using them would certainly make a switch over easier 😄 

Had a quick toy around with getting them to work, which I am happy to put a PR in for, however, I need to look further into being able to use the `afterCreatingState` functionality, or a nice alternative, as I also use them quite a lot

**Comment by lukeraymonddowning** [comment]
Sounds like a plan! Send a PR, and we'll work through it together. I want to utilize the existing Laravel Factories as much as possible
