### ISSUE TITLE
After Creating feature

### ISSUE THREAD

**Issue by AlanHolmes** [lukeraymonddowning/poser#19]
Something that I have used quite heavily on the Laravel factories is the after creating functions (like `afterCreatingState`) that allow me to do certain actions after the records have been created.

It would be good if we could get something like this for Poser as well, where I could add an afterCreating closure to either the main record or any relationships.

An example of my use case is all my Users belong to a Company (one to many), but the company can have a single user marked as the main user. This is stored on the company table under `main_user_id`, and in my factory, I have a state `with_main_user` setup on the Company factory that looks like this:

```php
$factory->state(Company::class, 'with_main_user', function (Faker $faker) {
    return [];
})->afterCreatingState(Company::class, 'with_main_user', function ($company, $faker) {
    $user = factory(User::class)->create([
        'company_id' => $company->id,
    ]);

    $company->setMainUser($user);
});
```

So being able to do something like this would be pretty sweet:

```php
CompanyFactory::new()->withMainUser()->create();

// where withMainUser is a custom function in CompanyFactory

public function withMainUser($attributes = [])
{
    $this->withUsers(UserFactory::new()->afterCreating(function($user, $company) {
        $company->setMainUser($user);
    })->create(attributes));
}
```

**Comment by lukeraymonddowning** [comment]
This is great so far, but we need to solve the child relationships. At the moment, it could be quite unintuitive.
