### ISSUE TITLE
Code review questions

### ISSUE THREAD

**Issue by andreich1980** [lukeraymonddowning/poser#24]
I was thinking about writing tests for the package, so I dig into the code to understand it better.
I'm still a n00b in making packages.
So I'm wondering shouldn't we avoid using Laravel helpers that the package itself doesn't have access to?
In this line you use `collect()`. And IDE (VS Code) marks it as error (unknown function).
Maybe you should use `\Illuminate\Support\Collection::wrap([])` instead (since you already have `illuminate/support` as a dependency)?

https://github.com/lukeraymonddowning/poser/blob/3f3017d14d299874200e053883770c7b106c037e/src/Factory.php#L46

**Comment by lukeraymonddowning** [comment]
Hi @andreich1980. Not a bad call at all. I have a Laravel application that I use as the test bed for Poser, so tests do exist for every feature. However, unit tests would be much appreciated. I think you're right about the collect() global helper function.

**Comment by andreich1980** [comment]
I was wrong about `collect()`. It is declared in `illuminate\support\helpers.php` so I guess there's no need to replace it with `Collect::wrap`. Sorry.

**Comment by lukeraymonddowning** [comment]
> I was wrong about `collect()`. It is declared in `illuminate\support\helpers.php` so I guess there's no need to replace it with `Collect::wrap`. Sorry.

Don't be sorry! Thanks so much for supporting and contributing!!!

**Comment by lukeraymonddowning** [comment]
Would you like to take on the unit tests task? If not, I'll close the issue.

**Comment by andreich1980** [comment]
I'm looking around. I'll let you know if I could come around with some tests.
Closing for now.

**Comment by andreich1980** [comment]
_I'm opening this issue because it's a kind of related to code review..._

In the `CONTRIBUTING.md` you say that PRs must follow PSR-2 standard.
But you yourself don't follow it.

[class opening brace on the same line](https://github.com/lukeraymonddowning/poser/blob/f442d1e7e13465ef671599b203cb72aff57f5c78/src/Factory.php#L17)

![изображение](https://user-images.githubusercontent.com/17148882/76093653-6a55cc00-5fd2-11ea-9368-b2545007eb27.png)

[`elseif` instead of  `else if`](https://github.com/lukeraymonddowning/poser/blob/f442d1e7e13465ef671599b203cb72aff57f5c78/src/Factory.php#L176)

[no braces for `if` with single-line if body](https://github.com/lukeraymonddowning/poser/blob/f442d1e7e13465ef671599b203cb72aff57f5c78/src/Factory.php#L200)

![изображение](https://user-images.githubusercontent.com/17148882/76093868-bf91dd80-5fd2-11ea-9b59-1bcd193494a3.png)

**Comment by lukeraymonddowning** [comment]
You got me good sir. I agree wholeheartedly that we should be using PSR-2. Thanks for picking up on this. I'll sort and push out a compatible version asap

**Comment by andreich1980** [comment]
👌🏻 I think it's no hurry. Just not to forget.

**Comment by andreich1980** [comment]
Hey @lukeraymonddowning 

Why in the config file you call those `models_directory` and `factories_directory` when they are actually namespaces, aren't they?

**Comment by lukeraymonddowning** [comment]
Hi @andreich1980. Yes, they are. I was going to change it for the 2.0.0-beta release but it slipped my mind. I think I'm going to release a PATCH revision that changes the config to 'x_namespace' but is backward compatible with 'x_directory'. Then, when we have good enough reason for 3.0.0-beta, I'll remove completely.
