### ISSUE TITLE
IDE supported versions of relationship methods

### ISSUE THREAD

**Issue by lukeraymonddowning** [lukeraymonddowning/poser#34]
So, been thinking about how I can further improve relationship support. At the moment, we support `has[RelationshipMethodName]`, `with[RelationshipMethodName]` and `for[RelationshipMethodName]`. I really like this, and am very happy with how it is working out, but I'm always looking to take it to the next level.

In order to provide an alternate syntax that reads better in certain circumstances and has better IDE support, I am considering adding `has`, `with` methods to the Poser abstract Factory.

Here are some examples of the proposed syntax:

`UserFactory::new()->has(10, 'customers')->create()` - creates 10 customers, linked to the user
`UserFactory::new()->has('customers')->create()` - creates 1 customer, linked to the user
`UserFactory::new()->has(5, 'customers', ["name" => "Joe Bloggs"])->create()` - creates 5 customers, linked to the user and all called "Joe Bloggs"

Both the `has()` and `with()` methods would return the factory, so the IDE would understand chaining and suggest additional function calls.

@AlanHolmes can I get your honest opinion on the value of this?

**Comment by AlanHolmes** [comment]
That would certainly help with IDE support.

So far what I have been doing is adding the `@method` for the relationships that I am using, eg:

```php
/**
 * @method self withPermissions(\Illuminate\Support\Collection|\Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection|\Lukeraymonddowning\Poser\Factory|int|array $factoryOrModelOrCollectionOrArrayOrInteger = null, array $default = null)
 */
class UserFactory extends Factory
{
}
```

Only so long cause of the different data types that they can accept for the first param, but this certainly works (something I have been meaning to add to the docs).

but maybe this might be a more elegant solution, esp to those that don't like magic methods lol, and then with a note on how you can add IDE support for the dynamic relationships by manually adding a `@method` (or maybe even a command? `php artisan poser:relationship-documentation UserFactory withPermissions` (only a better name) that would add the docblock for you). - Food for thought.

Either way, I think your suggestion would certainly be worthwhile doing as well 😄

**Comment by lukeraymonddowning** [comment]
Okay, slight segue (and perhaps the discussion of a new issue). I was thinking of the doc stuff too the other day. How crazy would it be to have a flag on the `make:poser` (perhaps `php artisan make:poser -document`) command that looked through the related model, finds methods that return a `Relation` instance, then automatically creates docblocks for them?

**Comment by AlanHolmes** [comment]
I was trying to think myself over the weekend as well about a way to automate the adding of the relationship docblocks too.

And I like that solution, could maybe still make it a separate command that `make:poser` calls (like creating the database factory), so that it can be used to re-document the Poser Factory as you add more relationships, that way its not just helpful on the initial creation.

**Comment by lukeraymonddowning** [comment]
> I was trying to think myself over the weekend as well about a way to automate the adding of the relationship docblocks too.
> 
> And I like that solution, could maybe still make it a separate command that `make:poser` calls (like creating the database factory), so that it can be used to re-document the Poser Factory as you add more relationships, that way its not just helpful on the initial creation.

Sounds like you had a classic programmer's 'few days away' 🤣

**Comment by AlanHolmes** [comment]
Yeah 🤣

**Comment by lukeraymonddowning** [comment]
I've been playing with this in [this branch](https://github.com/lukeraymonddowning/poser/tree/ide_relationship_method_versions)

I don't know that I'm 100% happy with this, but can't explain why. Not merging in at the moment,, but may come back to this. Feel free to peruse/improve/suggest

**Comment by lukeraymonddowning** [comment]
Going to close this for now. Will reopen further down the road.
