### ISSUE TITLE
PSR-12 and PhpStorm

### ISSUE THREAD

**Issue by andreich1980** [lukeraymonddowning/poser#35]
Probably off-topic, sorry. 

I was checking the latest changes and tried to switch my PhpStorm to use PSR-12. 
Turned out that PhpStorm doesn't go right about [this rule](https://www.php-fig.org/psr/psr-12/#47-method-and-function-calls)
![изображение](https://user-images.githubusercontent.com/17148882/76296070-b51f5e80-62c6-11ea-92f8-ee76ac83d416.png)
Here we can read and see that 

> A single argument being split across multiple lines (as might be the case with an anonymous function or array) does not constitute splitting the argument list itself.
```php
$app->get('/hello/{name}', function ($name) use ($app) {
    return 'Hello ' . $app->escape($name);
});
```

But PhpStorm doesn't understand it and places **EACH** argument from this example on a new line that looks kinda ugly for me
![изображение](https://user-images.githubusercontent.com/17148882/76296203-e566fd00-62c6-11ea-8615-50e5b0614533.png)

I see the same story in the e1c70a25fc3a8e7779cdbbff1747344562706189:
```php
// before
        $this->call('make:factory', [
            'name' => "{$factory}Factory",
            '--model' => $this->qualifyClass($factory),
        ]);
// after
        $this->call(
            'make:factory',
            [
                'name' => "{$factory}Factory",
                '--model' => $this->qualifyClass($factory),
            ]
        );
```

Is there a way to fix this behavior? Or should I go to PhpStorm support?

**Comment by lukeraymonddowning** [comment]
It is possible that this could be resolved with a custom PhpStorm config, but that would require everybody who contributes to have the same config. I think this is more of a PhpStorm support problem
