### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by andreich1980** [lukeraymonddowning/poser#38]
I'm about to create a PR with some basic unit tests (just for starting point, will add more later). 
Should I PR to the `master` or you would create a new branch for that?
My fork https://github.com/andreich1980/poser/tree/tests

**Comment by lukeraymonddowning** [comment]
PR into master

**Comment by andreich1980** [comment]
Oh, you'd want to remove your private data from the response  😉 @lukeraymonddowning

**Comment by lukeraymonddowning** [comment]
Thanks! Emails are the worst and the best

**Comment by lukeraymonddowning** [comment]
Thanks so much @andreich1980!

**Comment by lukeraymonddowning** [comment]
@all-contributors please add @andreich1980 for test

**Comment by andreich1980** [comment]
Oh, I didn't change config keys `x_directory` to `x_namespace` so the tests are failed :/
I'll fix it soon.

**Comment by andreich1980** [comment]
Fixed in #41
