### ISSUE TITLE
Need a hand with testing

### ISSUE THREAD

**Issue by andreich1980** [lukeraymonddowning/poser#42]
My test is (I stole it from the README.md)
```php
    public function it_creates_many_user_with_address_and_many_customers()
    {
        UserFactory::times(3)
            ->withAttributes(['name' => 'test'])
            ->hasAddress()
            ->withCustomers(
                CustomerFactory::times(5)
            )
            ->create();

        $this->assertEquals(3, User::count());
        $this->assertEquals(3, Address::count());
        $this->assertEquals(15, Customer::count());
    }
```

All 3 factories are empty like this
```php
namespace Lukeraymonddowning\Poser\Tests\Factories;

use Lukeraymonddowning\Poser\Factory;

class XxxFactory extends Factory
{
}
```

Address and Customer database factories are like this
```php
$factory->define(
    Xxx::class,
    function (Faker $faker) {
        return [
            'field_1'  => $faker->something,
            'user_id' => factory(User::class),
            // 'user_id' => function () {
            //     return factory(User::class);
            // },
            // I have tried both ways
        ];
    }
);
```

My test fails at the line `$this->assertEquals(3, User::count());` with error `Failed asserting that 21 matches expected 3.`

It looks like it creates 3 users, then 3 new addresses (with a brand new user each) and then 15 customers with a brand new user each. 3+3+15=21 🤔

What am I missing?

**Comment by lukeraymonddowning** [comment]
If you remove the 'user_id' column from the Laravel factory entirely, what happens?

**Comment by lukeraymonddowning** [comment]
Also @andreich1980, do you have a Twitter handle?

**Comment by andreich1980** [comment]
> If you remove the 'user_id' column from the Laravel factory entirely, what happens?

It's weird. After I removed `user_id` column from Laravel Factories the test passes. How so?
And if I remove `user_id` from factories I couldn't test it this way
```php
$user = UserFactory::new()();
$customers = CustomerFactory::times(5)->withUser($user)();

$this->assertEquals(1, User::count());
$this->assertCount(1, $customers->map->user->map->id);
```
it fails with `SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: customers.user_id`

I have twitter but I prefer Telegram or WhatsApp. Tell me what do you choose and I'll DM you there (I've got your twitter and could find your phone number if you choose Tg).

**Comment by andreich1980** [comment]
> ```php
> $user = UserFactory::new()();
> $customers = CustomerFactory::times(5)->withUser($user)();
> 
> $this->assertEquals(1, User::count());
> $this->assertCount(1, $customers->map->user->map->id);
> ```

Maybe it's not allowed to do so at alll? Because I get `BadMethodCallException : Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::save()` when I returned `user_id` back in the CustomerFactory...

**Comment by lukeraymonddowning** [comment]
Hmmm. I'm going to take a dive into this and see what can be done 👍 Thanks for all your research @andreich1980. The Twitter handle was so that I could give you a shoutout to thank you for the work you're putting into the project. Is that okay?

**Comment by lukeraymonddowning** [comment]
So, the issue has been located. Poser calls `make` on the related models before handling the save() part. When make is called, the closure in the Laravel factory is resolved and a model is persisted to the database. I'm going to play around with some 'solutions'.

**Comment by andreich1980** [comment]
Great!
I DM'd you on Twitter
