### ISSUE TITLE
ToDo or RoadMap

### ISSUE THREAD

**Issue by andreich1980** [lukeraymonddowning/poser#60]
If you create either of these files someone could help you to implement some stuff.

**Comment by lukeraymonddowning** [comment]
Agreed and thank you, I'll get one added. If you have any ideas BTW, please add them and I'll put them in the roadmap 👍

**Comment by andreich1980** [comment]
I haven't got any so I suggested to add a file for ideas lol

**Comment by lukeraymonddowning** [comment]
I've added TODO.md

It only has a couple of things in at the moment, but I'll add more as I come to them 👍
