### ISSUE TITLE
Deprecation Notice: haydenpierce/class-finder

### ISSUE THREAD

**Issue by andreich1980** [lukeraymonddowning/poser#70]
I'm installing the package to my laravel project
```
  - Installing haydenpierce/class-finder (0.4.0): Loading from cache
  - Installing lukeraymonddowning/poser (2.8.0-beta): Loading from cache Writing lock file
Generating optimized autoload files
Deprecation Notice: Class HaydenPierce\ClassFinder\UnitTest\Files\FilesTest 
located in ./vendor/haydenpierce/class-finder/test/unit/Files/FilesEntryTest.php 
does not comply with psr-4 autoloading standard. 
It will not autoload anymore in Composer v2.0. 
in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

**Comment by lukeraymonddowning** [comment]
@andreich1980 do you have time to submit a PR to haydenpierce/class-finder? If not, I'll take a look. Not got much time for the rest of this week.

**Comment by andreich1980** [comment]
I'll take a look.

**Comment by andreich1980** [comment]
It's been fixed a week ago in the master but hasn't been tagged yet. The current version is still 0.4.0.
I've created an issue https://gitlab.com/hpierce1102/ClassFinder/-/issues/13#related-issues

**Comment by lukeraymonddowning** [comment]
You're awesome, thanks @andreich1980

**Comment by andreich1980** [comment]
You might want to like/suppert the issue I created there. The maintainer said that `notification is harmless` :(

**Comment by lukeraymonddowning** [comment]
I've put in my 2 cents 👍

**Comment by andreich1980** [comment]
It's been fixed.
