### ISSUE TITLE
make:poser Suggestions

### ISSUE THREAD

**Issue by AlanHolmes** [lukeraymonddowning/poser#8]
### IDE Autocomplete

Wanted to pass this by you before going ahead, as it seems a big thing that the generated factories are empty, but what do you think about changing the command so that it generates something like this

```php
class ClientFactory extends Factory
{
    /**
     * @param array $attributes
     *
     * @return \Illuminate\Support\Collection|\Illuminate\Database\Eloquent\Collection|\App\Client[]|\App\Client
     */
    public function create($attributes = [])
    {
        return parent::create($attributes);
    }

    /**
     * @param array $attributes
     *
     * @return \Illuminate\Support\Collection|\Illuminate\Database\Eloquent\Collection|\App\Client[]|\App\Client
     */
    public function make($attributes = [])
    {
        return parent::make($attributes);
    }
}
```

It doesn't contain any logic, but it helps with IDE auto-complete.

### Laravel factories

How about adding an option to the command to also generate the Laravel factory as well (similar to how you can with the `make:model -f` command)

**Comment by AlanHolmes** [comment]
With the auto complete, you could add the following the core factory `create` and `make` methods to give some completion for existing classes too

```php
/**
     * @param array $attributes
     *
     * @return \Illuminate\Support\Collection|\Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model[]|\Illuminate\Database\Eloquent\Model
     */
     public function create($attributes = [])
    {
        // ...
    }
```

**Comment by lukeraymonddowning** [comment]
I like it. I wish we didn’t have to, but you’re right in saying IDE autocomplete is more important. Proposal: we have an —empty flag that you can pass the command to generate a completely empty factory, but by default it adds the create and make calls

**Comment by lukeraymonddowning** [comment]
> With the auto complete, you could add the following the core factory `create` and `make` methods to give some completion for existing classes too
> 
> ```
> /**
>      * @param array $attributes
>      *
>      * @return \Illuminate\Support\Collection|\Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model[]|\Illuminate\Database\Eloquent\Model
>      */
>      public function create($attributes = [])
>     {
>         // ...
>     }
> ```

Definitely this

**Comment by AlanHolmes** [comment]
yeah an `--empty` flag would be a good compromise for this.

Also, just thought of another one as well, a flag for model for setting `$modelName` (which will be needed if we are adding the autocomplete stuff)

**Comment by lukeraymonddowning** [comment]
> yeah an `--empty` flag would be a good compromise for this.
> 
> Also, just thought of another one as well, a flag for model for setting `$modelName` (which will be needed if we are adding the autocomplete stuff)

Sounds like a plan. Do you want to take this or shall I?

**Comment by AlanHolmes** [comment]
I'm happy to look at this, will try later today 😄

**Comment by veganista** [comment]
Can you do this with doc-bloc comments?

```php
/**
  * @method string getString()
  * @method void setInteger(integer $integer)
  * @method setString(integer $integer)
  * @method static string staticGetter()
  */
 class Child extends Parent
 {
     <...>
 }
```

https://docs.phpdoc.org/latest/references/phpdoc/tags/method.html

**Comment by lukeraymonddowning** [comment]
> Can you do this with doc-bloc comments?
> 
> ```
> /**
>   * @method string getString()
>   * @method void setInteger(integer $integer)
>   * @method setString(integer $integer)
>   * @method static string staticGetter()
>   */
>  class Child extends Parent
>  {
>      <...>
>  }
> ```
> 
> https://docs.phpdoc.org/latest/references/phpdoc/tags/method.html

I prefer this @AlanHolmes

**Comment by AlanHolmes** [comment]
@veganista good call

I was adding these `@method` docblocks for the dynamic relationships too

That method could mean that we can forgo the need for the empty flag too

**Comment by lukeraymonddowning** [comment]
> @veganista good call
> 
> I was adding these `@method` docblocks for the dynamic relationships too
> 
> That method could mean that we can forgo the need for the empty flag too

Seems like the best option.

**Comment by veganista** [comment]
Glad i mentioned it!

Absolutely can't wait to try and use this in my current project.

**Comment by lukeraymonddowning** [comment]
@all-contributors please add @veganista for ideas
