### ISSUE TITLE
Has Many relationship stuck while running the test case

### ISSUE THREAD

**Issue by bugudiamshu** [lukeraymonddowning/poser#81]
The credential has many CredentialLevels. I have Credential and CredentialLevel models. Also, have the CredentialFactory and CredentialLevelFactory classes as provided in the readme. But, while running the test case, it is stuck (showing dot) in the CLI and doesn't throw any error. 

This is the test case
```
   /** @test */
   public function credential_has_many_credential_levels()
   {
      $credential = CredentialFactory::new()
                                    ->withCredentialLevels(CredentialLevelFactory::items(2))
                                    ->create();

      $this->assertCount(2, $credential->credentialLevels);
   }
```

**Comment by lukeraymonddowning** [comment]
Hullo! Sorry for the delay in replying. I think you’ve got a typo. You’ve put ‘items()’ instead of ‘times()’. 

Thanks for using Poser!
