### ISSUE TITLE
Publishing the config

### ISSUE THREAD

**Issue by andreich1980** [lukeraymonddowning/poser#9]
According to `README.md` we should run a command
```
php artisan vendor:publish
```
But this will public **ALL** _publicable_ stuff from **ALL** packages I use in my app.
It would be cool to public only things I want to public.
For example
```
php artisan vendor:publish --tag=lukeraymonddowning/poser
```
or just 
```
php artisan vendor:publish --tag=poser
```
I might make a PR if you're OK with that.

**Comment by lukeraymonddowning** [comment]
Thanks @andreich1980, please PR and I'll merge it

**Comment by lukeraymonddowning** [comment]
All sorted. Great work @andreich1980
